trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'
  
- script: |
    npx cypress run --spec cypress/e2e/features/* --env tags=@mobile
  displayName: 'run e2e tests'
  continueOnError: true

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/output.xml'
    mergeTestResults: true
    testRunTitle: 'publish test results'
- task: publishhtmlreport@1
  inputs:
    htmlType: 'genericHTML'
    htmlPath: '$(Build.SourcesDirectory)/cypress/reports/index.html'
- task: CmdLine@2
  inputs:
    script: 'ls'
    workingDirectory: '$(System.DefaultWorkingDirectory)/cypress/reports/'